// Generated by IcedCoffeeScript 108.0.9
(function() {
  app.controller('IndexCtrl', function($scope, fhirServer, resourceIdentityModel) {
    var fpath, server;
    fpath = null;
    require(['Client/app/vendor/fhirpath.js/bundle.js'], function(fhirpath) {
      return fpath = fhirpath;
    });
    server = fhirServer(resourceIdentityModel.BaseUrl);
    server.read({
      id: resourceIdentityModel.ResourceId,
      resourceType: resourceIdentityModel.ResourceType,
      success: function(data) {
        $scope.resource = JSON.stringify(data, null, 4);
        return $scope.$apply('doMapping()');
      },
      error: function(error) {
        return console.log(error);
      }
    });
    $scope.showReturnButton = function() {
      return resourceIdentityModel.CallbackUrl !== null;
    };
    $scope.goBack = function() {
      return window.location = resourceIdentityModel.CallbackUrl;
    };
    $scope.update = function() {
      var e, resource, result;
      try {
        resource = JSON.parse($scope.resource);
        $scope.parseError = null;
      } catch (_error) {
        e = _error;
        $scope.parseError = e.toString();
        return;
      }
      try {
        result = fpath.evaluate(resource, $scope.path);
        $scope.result = JSON.stringify(result, null, "  ");
        $scope.errors = null;
        $scope.error = null;
        return $scope.successMessage = "Your fluent path compliles correctly.";
      } catch (_error) {
        e = _error;
        if (e.errors) {
          $scope.successMessage = null;
          $scope.error = null;
          $scope.errors = e.errors;
          return console.log("ERROR", e.errors);
        } else {
          $scope.successMessage = null;
          $scope.errors = null;
          return $scope.error = e.toString();
        }
      }
    };
    return $scope.codemirrorConfig = {
      lineWrapping: false,
      lineNumbers: true,
      mode: 'javascript',
      extraKeys: window.CodeMirror.normalizeKeyMap({
        "Ctrl-Space": function() {
          return $scope.$apply('doMapping()');
        },
        Tab: function(cm) {
          return cm.replaceSelection("  ");
        }
      }),
      viewportMargin: Infinity
    };
  });

}).call(this);
