// Generated by IcedCoffeeScript 108.0.9
(function() {
  app.controller('IndexCtrl', function($scope, fhirServer, resourceReferenceModel) {
    var codemirrorExtraKeys, fpath;
    fpath = null;
    require(['Client/app/vendor/fhirpath.js/bundle.js'], function(fhirpath) {
      return fpath = fhirpath;
    });
    $scope.path = "";
    $scope.resource = "";
    fhirServer(resourceReferenceModel.BaseUrl).read({
      id: resourceReferenceModel.ResourceId,
      resourceType: resourceReferenceModel.ResourceType,
      success: function(data) {
        $scope.resource = JSON.stringify(data);
        return $scope.$apply('doMapping()');
      },
      error: function(error) {
        return console.log(error);
      }
    });
    $scope.update = function() {
      var e, resource, result;
      try {
        resource = JSON.parse($scope.resource);
        $scope.parseError = null;
      } catch (_error) {
        e = _error;
        $scope.parseError = e.toString();
        return;
      }
      try {
        result = fpath.evaluate(resource, $scope.path);
        $scope.result = JSON.stringify(result, null, "  ");
        $scope.errors = null;
        return $scope.error = null;
      } catch (_error) {
        e = _error;
        if (e.errors) {
          $scope.errors = e.errors;
          return console.log("ERROR", e.errors);
        } else {
          return $scope.error = e.toString();
        }
      }
    };
    codemirrorExtraKeys = window.CodeMirror.normalizeKeyMap({
      "Ctrl-Space": function() {
        return $scope.$apply('doMapping()');
      },
      Tab: function(cm) {
        return cm.replaceSelection("  ");
      }
    });
    return $scope.codemirrorConfig = {
      lineWrapping: false,
      lineNumbers: true,
      mode: 'javascript',
      extraKeys: codemirrorExtraKeys,
      viewportMargin: Infinity
    };
  });

}).call(this);
