// Generated by IcedCoffeeScript 108.0.9
(function() {
  window.app = angular.module('app', ['ngCookies', 'ngRoute', 'ngAnimate', 'ui.codemirror']);

  app.factory("fhirServer", function() {
    var fhirServer;
    fhirServer = function(url) {
      var client, clientConfig;
      clientConfig = {
        baseUrl: url
      };
      client = fhir(clientConfig, jqAdapter);
      return client;
    };
    return fhirServer;
  });

  app.run(function($rootScope, $window) {
    return console.log('run');
  });

  app.config(function($routeProvider) {
    var rp;
    rp = $routeProvider;
    rp.when('/', {
      name: 'index',
      templateUrl: 'Client/app/partials/_index.html',
      controller: 'IndexCtrl',
      resolve: {
        resourceIdentityModel: function(resourceIdentityModel, $location) {
          if (resourceIdentityModel === null) {
            return $location.path("error");
          } else {
            return resourceIdentityModel;
          }
        }
      },
      reloadOnSearch: false
    });
    return rp.otherwise({
      templateUrl: 'Client/app/partials/404.html'
    });
  });

}).call(this);
